name: Deploy to GitHub Pages

# Triggers the workflow on push events to the main branch
on:
  push:
    branches: [ main ] # Or your default branch if it's not 'main' (e.g., master)

# Sets permissions for the GitHub token to allow deployment to GitHub Pages
permissions:
  contents: write # Allows the action to push to the gh-pages branch

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository's code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specifies Node.js version 20.x
          cache: 'npm' # Enables caching for npm dependencies

      - name: Install dependencies
        # 'npm ci' is generally recommended for CI for faster, more reliable installs
        # It uses package-lock.json and ensures a clean slate
        run: npm ci 

      - name: Build application
        # This runs the 'build' script defined in your package.json
        run: npm run build 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # Uses a popular action for deployment
        with:
          branch: gh-pages # The branch the action should deploy to.
          # This is the CRUCIAL part that needs to match your Vite build output directory:
          folder: dist/public # Your vite.config.ts specifies outDir as 'dist/public'
